# # # # GOOGLE NLP API TOKENS # # # #
GOOGLE_API_KEY = "YOURKEYHERE"
GOOGLE_ACCESS_TOKEN = "YOURKEYHERE"

# # # # TWITTER ACCESS TOKENS # # # #
TWITTER_ACCESS_TOKEN = "YOURKEYHERE"
TWITTER_ACCESS_TOKEN_SECRET = "YOURKEYHERE"
TWITTER_CONSUMER_KEY = "YOURKEYHERE"
TWITTER_CONSUMER_SECRET = "YOURKEYHERE"